
stages:
  - name: prepare
    tasks:
      - image: registry.core.build-the-web.com/devine:0.1.4
        script: devine pipeline prepare --pipeline-id "${PIPELINE_ID}" --base-dir "${BASE_DIR}"

  - name: clone
    tasks:
      - image: registry.core.build-the-web.com/devine:0.1.4
        script: github clone repo --pipeline-id "${PIPELINE_ID}" --base-dir "${BASE_DIR}"

  - name: parse
    tasks:
      - image: registry.core.build-the-web.com/devine:0.1.4
        script: devine pipeline run --pipeline-id "${PIPELINE_ID}" --base-dir "${BASE_DIR}"

  - name: cleanup
    tasks:
      - image: registry.core.build-the.web.com/devine:0.1.4
        script: devine pipeline clean --pipeline-id "${PIPELINE_ID}" --base-dir "${BASE_DIR}"
