
stages:
  - name: prepare
    tasks:
      - image: registry.core.build-the-web.com/devine:0.1.0
        script: devine pipeline prepare

  - name: clone
    tasks:
      - image: registry.core.build-the-web.com/devine:0.1.0
        script: github clone repo

  - name: parse
    tasks:
      - image: registry.core.build-the-web.com/devine:0.1.0
        script: devine pipeline run

  - name: cleanup
    tasks:
      - image: registry.core.build-the.web.com/devine:0.1.0
        script: devine pipeline clean
